'''
Created on 5 Aug 2013

@author: fsaracino
'''

# ********************************************************************************************
# Error table definition
# ********************************************************************************************
#Test errors
ERRCODE_TEST_PASS                 = 0
ERRCODE_TEST_FAILURE              = 1
ERRCODE_TEST_TIMEOUT              = 2
ERRCODE_TEST_PARAM_INVALID        = 3

ERRCODE_TEST_FAILURE_REFTHR       = 4
ERRCODE_TEST_FAILURE_ATTACH       = 5
ERRCODE_TEST_FAILURE_CEST         = 6
ERRCODE_TEST_FAILURE_INTRAHO      = 7
ERRCODE_TEST_FAILURE_PARAMCONFIG  = 8

# System errors
ERRCODE_SYS_CMW_CONN                 = 20
ERRCODE_SYS_CMW_INVMEAS              = 21
ERRCODE_SYS_CMW_TIMEOUT              = 22
ERRCODE_SYS_CMW_CONNECTION_LOST      = 23
ERRCODE_SYS_CMW_INCORRECT_SW_VERSION = 24
ERRCODE_SYS_SERIAL_CONN              = 25
ERRCODE_SYS_SOCKET_CONN              = 26
ERRCODE_SYS_FILE_IO                  = 27
ERRCODE_SYS_DUT_TIMEOUT              = 28
ERRCODE_SYS_ICAL_FAILURE             = 29
ERRCODE_SYS_ICAL_PARAMCONFIG         = 30
ERRCODE_SYS_PSU_CONNECTION_FAILURE   = 31
ERRCODE_SYS_COM_FAILURE              = 32

error_table={ 
  ERRCODE_TEST_PASS                    : 'PASS',
  ERRCODE_TEST_FAILURE                 : 'FAILURE',
  ERRCODE_TEST_TIMEOUT                 : 'TIMEOUT',
  ERRCODE_TEST_PARAM_INVALID           : 'INVALID PARAMETER',
  
  ERRCODE_TEST_FAILURE_REFTHR          : 'REFERENCE_THROUGHPUT_FAILURE',
  ERRCODE_TEST_FAILURE_ATTACH          : 'ATTACH_FAILURE',
  ERRCODE_TEST_FAILURE_CEST            : 'CONNECTION_ESTABLISHMENT_FAILURE',
  ERRCODE_TEST_FAILURE_INTRAHO         : 'CONNECTION_FAILURE_AFTER_INTRA_CELL_HO',
  ERRCODE_TEST_FAILURE_PARAMCONFIG     : 'TEST_PARAMETER_CONFIGURATION_ERROR',
  
  ERRCODE_SYS_CMW_CONN                 : 'CMW500_CONNECTION_FAILURE',
  ERRCODE_SYS_CMW_INVMEAS              : 'CMW500_INVALID_MEASUREMENTS',
  ERRCODE_SYS_CMW_TIMEOUT              : 'CMW500_INVALID_TIMEOUT',
  ERRCODE_SYS_CMW_CONNECTION_LOST      : 'UE_CONNECTION_LOST_DURING_MEASUREMENT_PERIOD',
  ERRCODE_SYS_CMW_INCORRECT_SW_VERSION : 'CMW500_INVALID_SW_VERSION_DETECTED',
  
  ERRCODE_SYS_SERIAL_CONN              : 'SERIAL_CONNECTION_COMMUNICATION_ERROR',
  ERRCODE_SYS_SOCKET_CONN              : 'SOCKET_CONNECTION_COMMUNICATION_ERROR',
  ERRCODE_SYS_FILE_IO                  : 'FILE_IO_OPERATION_ERROR',
 
  ERRCODE_SYS_DUT_TIMEOUT              : 'ERRCODE_SYS_DUT_TIMEOUT',
  ERRCODE_SYS_ICAL_FAILURE             : 'ERRCODE_SYS_ICAL_FAILURE',
  ERRCODE_SYS_ICAL_PARAMCONFIG         : 'ERRCODE_SYS_ICAL_PARAMCONFIG', 
  ERRCODE_SYS_PSU_CONNECTION_FAILURE   : 'ERRCODE_SYS_PSU_CONNECTION_FAILURE',
  ERRCODE_SYS_COM_FAILURE              : 'ERRCODE_SYS_COM_FAILURE'
}


if __name__ == '__main__':

    for (k, v) in error_sysexit_table.items():
        print ">> errorcode=%s, description=%s" % (k, v)
    